"""added foreign key to conversation message

Revision ID: 168594846ed1
Revises: d7adb79f16a5
Create Date: 2026-01-10 15:35:08.746883

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "168594846ed1"
down_revision: Union[str, Sequence[str], None] = "d7adb79f16a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations_messages",
        sa.Column("conversation_id", sa.String(), nullable=False),
    )
    op.create_foreign_key(
        None, "conversations_messages", "conversations", ["conversation_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "conversations_messages", type_="foreignkey")
    op.drop_column("conversations_messages", "conversation_id")
    # ### end Alembic commands ###
