"""new status field on Conversation model

Revision ID: 168ecf6b38d2
Revises: 492c4c2eda43
Create Date: 2026-01-10 17:40:49.547058

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "168ecf6b38d2"
down_revision: Union[str, Sequence[str], None] = "492c4c2eda43"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversations", sa.Column("status", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "status")
    # ### end Alembic commands ###
