"""upaded conversation event

Revision ID: 311c62361fba
Revises: e9d62c30d3c3
Create Date: 2026-01-09 20:25:34.139423

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "311c62361fba"
down_revision: Union[str, Sequence[str], None] = "e9d62c30d3c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations_events", sa.Column("type", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations_events", "type")
    # ### end Alembic commands ###
