"""outbox has reference to events table

Revision ID: 492c4c2eda43
Revises: a553303195c6
Create Date: 2026-01-10 17:01:58.282813

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "492c4c2eda43"
down_revision: Union[str, Sequence[str], None] = "a553303195c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversation_outbox", sa.Column("event_id", sa.String(), nullable=False)
    )
    op.create_foreign_key(
        None, "conversation_outbox", "conversations_events", ["event_id"], ["id"]
    )
    op.drop_column("conversation_outbox", "conversation_id")
    op.drop_column("conversation_outbox", "payload")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversation_outbox",
        sa.Column(
            "payload",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "conversation_outbox",
        sa.Column("conversation_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "conversation_outbox", type_="foreignkey")
    op.drop_column("conversation_outbox", "event_id")
    # ### end Alembic commands ###
