"""updated models

Revision ID: 8f0be99713e3
Revises: 50ede0b32c1d
Create Date: 2026-01-10 20:13:45.529196

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f0be99713e3"
down_revision: Union[str, Sequence[str], None] = "50ede0b32c1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column(
        "conversations_messages", sa.Column("text", sa.String(), nullable=False)
    )
    op.add_column(
        "conversations_messages", sa.Column("sender", sa.String(), nullable=False)
    )
    op.add_column(
        "conversations_messages", sa.Column("version", sa.Integer(), nullable=False)
    )
    op.add_column(
        "conversations_messages",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_foreign_key(
        None, "conversations_messages", "users", ["sender"], ["email"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "conversations_messages", type_="foreignkey")
    op.drop_column("conversations_messages", "created_at")
    op.drop_column("conversations_messages", "version")
    op.drop_column("conversations_messages", "sender")
    op.drop_column("conversations_messages", "text")
    op.drop_column("conversations", "created_at")
    # ### end Alembic commands ###
