"""dropped foreign key from conversation_id in outbox table

Revision ID: a553303195c6
Revises: 168594846ed1
Create Date: 2026-01-10 15:58:46.913624

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a553303195c6"
down_revision: Union[str, Sequence[str], None] = "168594846ed1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("conversation_outbox_conversation_id_fkey"),
        "conversation_outbox",
        type_="foreignkey",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("conversation_outbox_conversation_id_fkey"),
        "conversation_outbox",
        "conversations",
        ["conversation_id"],
        ["id"],
    )
    # ### end Alembic commands ###
