"""added risk analysis model

Revision ID: cc2476e2c13d
Revises: 8f0be99713e3
Create Date: 2026-01-11 01:24:27.413604

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cc2476e2c13d"
down_revision: Union[str, Sequence[str], None] = "8f0be99713e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_analyses",
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("analysis", sa.JSON(), nullable=False),
        sa.Column("detected_risk", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("conversation_analyses")
    # ### end Alembic commands ###
