"""apply unique constraint

Revision ID: d7adb79f16a5
Revises: 775b35becee5
Create Date: 2026-01-10 14:55:29.952208

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d7adb79f16a5"
down_revision: Union[str, Sequence[str], None] = "775b35becee5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_conversation_id_version",
        "conversations_events",
        ["conversation_id", "version"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_conversation_id_version", "conversations_events", type_="unique"
    )
    # ### end Alembic commands ###
